name: new issue

on:
  issues

jobs:
  send_slack_msg:
    name: send slack message
    runs-on: ubuntu-latest
    steps:
      - name: print info
        run: |
          echo 'event: ${{ github.event_name }}'
          echo 'action: ${{ github.event.action }}'
          echo 'title: ${{ github.event.issue.title }}'
          echo 'body: ${{ github.event.issue.body }}'
          echo 'repo_name: ${{ github.event.repository.name }}'          
          echo "test contains: ${{ contains('https://hooks.slack.com/workflows/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', 'https://hooks.slack.com/workflows/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') }}"
          echo "slack_webhook_url: ${{ contains(secrets.SLACK_WEBHOOK_AFTERSHIP_SDK_ISSUE, 'https://hooks.slack.com/workflows/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') }}"
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.19.0
        with:
          payload: |
            {
              "issue_title": "${{ github.event.issue.title }}",
              "issue_body": "${{ github.event.issue.body }}",
              "issue_html_url": "${{ github.event.issue.html_url }}",
              "repo_name": "${{ github.event.repository.name }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_AFTERSHIP_SDK_ISSUE }}
    
          
