name: new issue

on:
  issues

jobs:
  print_msg:
    name: print_msg
    runs-on: ubuntu-latest
    steps:
      - name: print
        run: |
          echo 'event: ${{ github.event_name }}'
          echo 'action: ${{ github.event.action }}'
          echo 'title: ${{ github.event.issue.title }}'
          echo 'body: ${{ github.event.body }}'
          echo 'repo: ${{ toJson(github.event.repository) }}'
    
          
