name: new issue

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  pr_send_slack_msg:
    name: send slack message
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: print PR info
        run: |
          echo 'event: ${{ github.event_name }}'
          echo 'action: ${{ github.event.action }}'
          echo 'repo_name: ${{ github.event.repository.name }}'
          echo 'pr_url: ${{ github.event.pull_request.url }}'
      - name: send pull request to slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.19.0
        with:
          payload: |
            {
              "issue_title": "${{ github.event.pull_request.title }}",
              "issue_body": "${{ github.event.pull_request.title }}",
              "issue_html_url": "${{ github.event.pull_request.url }}",
              "repo_name": "${{ github.event.repository.name }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_SDK_V2 }}
          
  issue_send_slack_msg:
    name: send slack message for issue
    if: github.event_name == 'issues'
    runs-on: ubuntu-latest
    steps:
      - name: print Issue info
        run: |
          echo 'event: ${{ github.event_name }}'
          echo 'action: ${{ github.event.action }}'
          echo 'repo_name: ${{ github.event.repository.name }}'
          echo 'issue_html_url: ${{ github.event.issue.html_url }}'
      - name: send issue to slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.19.0
        with:
          payload: |
            {
              "issue_title": "${{ github.event.issue.title }}",
              "issue_body": "${{ github.event.issue.body }}",
              "issue_html_url": "${{ github.event.issue.html_url }}",
              "repo_name": "${{ github.event.repository.name }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_SDK_V2 }}
    
          
