name: new issue

on:
  issues

jobs:
  print_msg:
    name: print_msg
    runs-on: ubuntu-latest
    steps:
      - name: print
        run: |
          echo '${{ github.event_name }}'
          echo '${{ github.event.issue }}'
          echo 'action: ${{ github.event.action }}'
          echo 'changes: ${{ github.event.changes }}'
          echo 'assignee: ${{ github.event.assignee }}'
          echo 'label: ${{ github.event.label }}'
          echo 'title: ${{ github.event.issue.title }}'
          echo 'description: ${{ github.event.issue.description }}'
          
