name: new issue

on:
  issues:
    types: [opened]

jobs:
  send_slack_msg:
    name: send slack message
    runs-on: ubuntu-latest
    steps:
      - name: print info
        run: |
          echo 'event: ${{ github.event_name }}'
          echo 'action: ${{ github.event.action }}'
          echo 'title: ${{ github.event.issue.title }}'
          echo 'body: ${{ github.event.issue.body }}'
          echo 'repo_name: ${{ github.event.repository.name }}'
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.19.0
        with:
          payload: |
            {
              "issue_title": "${{ github.event.issue.title }}",
              "issue_body": "${{ github.event.issue.body }}",
              "issue_html_url": "${{ github.event.issue.html_url }}",
              "repo_name": "${{ github.event.repository.name }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_SDK_V2 }}
    
          
