name: new issue

on:
  issues

jobs:
  print_msg:
    name: print_msg
    runs-on: ubuntu-latest
    steps:
      - name: print
        run: |
          echo '${{ github.event_name }}'
          echo '${{ github.event.issue }}'
          echo '${{ github.event.action }}'
          echo '${{ github.event.changes }}'
          echo '${{ github.event.assignee }}'
          echo '${{ github.event.label }}'
          
